services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./src/Dockerfile
    command: ["pm2-runtime", "start", "--interpreter", "tsx", "server.ts"]
    ports:
      - "3000:3000"
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - token-worker

  redis:
    image: redis:alpine
    container_name: redis-schedule-panel
    restart: always
    env_file:
      - ./.env.prod
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  token-worker:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: token-worker
    command: ["pm2-runtime", "start", "/usr/src/jobs/workers/tokenWorker.ts", "--interpreter", "tsx", "--instances", "1"]
    env_file:
      - ./.env.prod
    depends_on:
      - redis

  vehicle-worker:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    container_name: vehicle-worker
    command: ["pm2-runtime", "start", "/usr/src/jobs/workers/vehicleWorker.ts", "--interpreter", "tsx", "--instances", "1"]
    env_file:
      - ./.env.prod
    depends_on:
      - redis
